/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#005ab7", 
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary": "#72554b",
        "inverse-on-surface": "#f0f0f2",
        "primary-fixed": "#d7e2ff",
        "primary-fixed-dim": "#abc7ff",
        "background": "#f9f9fb",
        "tertiary-container": "#8d6e63",
        "secondary-fixed": "#c9e7f7",
        "surface-bright": "#f9f9fb",
        "error": "#ba1a1a",
        "tertiary-fixed": "#ffdbce",
        "on-tertiary-fixed-variant": "#5b4137",
        "outline": "#717786",
        "inverse-primary": "#abc7ff",
        "surface-dim": "#d9dadc",
        "on-background": "#1a1c1d",
        "on-secondary-fixed-variant": "#2e4b57",
        "on-surface": "#1a1c1d",
        "surface-container-high": "#e8e8ea",
        "surface": "#f9f9fb",
        "primary-container": "#0372e4",
        "on-primary-fixed": "#001b3f",
        "on-primary-container": "#fefcff",
        "surface-container": "#eeeef0",
        "tertiary-fixed-dim": "#e4beb2",
        "on-primary-fixed-variant": "#00458f",
        "secondary-fixed-dim": "#adcbda",
        "surface-container-highest": "#e2e2e4",
        "inverse-surface": "#2f3132",
        "secondary-container": "#c6e4f4",
        "on-secondary-fixed": "#001f2a",
        "surface-tint": "#005cbb",
        "secondary": "#466270",
        "on-tertiary-fixed": "#2b160f",
        "surface-variant": "#e2e2e4",
        "surface-container-low": "#f3f3f5",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#4a6774",
        "on-secondary": "#ffffff",
        "outline-variant": "#c1c6d7",
        "on-tertiary-container": "#fffbff",
        "on-surface-variant": "#414755",
        "on-error": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
    },
  },
  plugins: [],
}
