-- 1. PROFILES TABLE
create table profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text,
  role text default 'user',
  created_at timestamp default now()
);

-- 2. PLACES TABLE
create table places (
  id bigint generated by default as identity primary key,
  name text,
  description text,
  category text,
  latitude double precision,
  longitude double precision,
  image_url text,
  created_by uuid references profiles(id),
  created_at timestamp default now()
);

-- 3. TRIPS TABLE
create table trips (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id),
  date date,
  created_at timestamp default now()
);

-- 4. TRIP_PLACES TABLE
create table trip_places (
  id bigint generated by default as identity primary key,
  trip_id bigint references trips(id) on delete cascade,
  place_id bigint references places(id),
  order_number integer
);

ALTER TABLE places
ADD COLUMN visit_duration_minutes INTEGER,
ADD COLUMN opening_hours TEXT;